#!/bin/sh

set -e

case "$1" in
    configure)
        chown nobody:nogroup /www/camera-filter/alarm
        chown nobody:nogroup /www/camera-filter/input
        chown nobody:nogroup /www/camera-filter/log
        chown nobody:nogroup /www/camera-filter/trash
        chown nobody:nogroup /www/camera-filter/error
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
